version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: ${DB_PASSW}
      POSTGRES_DB: telegram_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}


  bot:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./src:/app
      - ./session:/app/session
      - ./misc:/app/misc
    env_file:
      - ./misc/config/passwd.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://bot:${DB_PASSW}@postgres:${DB_PORT}/telegram_db
    command: ["python", "/app/main.py"]

volumes:
  pgdata:
